"""add emergency, asset, and vessel tracking foundations"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry
revision="20260926_0006"; down_revision=("20260926_0005", "8a8f27c19e10"); branch_labels=None; depends_on=None
P=postgresql.UUID(as_uuid=True); J=postgresql.JSONB(astext_type=sa.Text()); STATUS="'observed','forecast','predicted','simulated','demo','provisional','invalid'"
def provenance(): return [sa.Column("source",sa.String(255),nullable=False),sa.Column("source_id",sa.String(255)),sa.Column("source_type",sa.String(64),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True)),sa.Column("ingested_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("processing_version",sa.String(128)),sa.Column("data_status",sa.String(32),nullable=False),sa.Column("confidence",sa.Numeric(5,4)),sa.Column("metadata_json",J),sa.CheckConstraint(f"data_status IN ({STATUS})",name=None)]
def upgrade():
 op.create_table("emergency_incidents",sa.Column("id",P,primary_key=True),sa.Column("incident_type",sa.String(64),nullable=False),sa.Column("severity",sa.String(16),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("description",sa.Text,nullable=False),sa.Column("reported_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("position",Geometry("POINT",srid=4326)),sa.Column("affected_vessel_id",P,sa.ForeignKey("vessels.id",ondelete="SET NULL")),sa.Column("affected_station_id",P,sa.ForeignKey("stations.id",ondelete="SET NULL")),sa.Column("people_affected",sa.Integer),*provenance(),sa.CheckConstraint("severity IN ('critical','high','medium','low')",name="ck_emergency_severity"),sa.CheckConstraint("status IN ('reported','acknowledged','assessing','response_dispatched','responding','resolved','cancelled')",name="ck_emergency_status"))
 op.create_table("emergency_events",sa.Column("id",P,primary_key=True),sa.Column("incident_id",P,sa.ForeignKey("emergency_incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("actor",sa.String(128),nullable=False),sa.Column("description",sa.Text,nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),*provenance())
 op.create_table("emergency_resources",sa.Column("id",P,primary_key=True),sa.Column("catalog_id",sa.String(128),unique=True,nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("resource_type",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("position",Geometry("POINT",srid=4326)),sa.Column("capacity",sa.Integer),sa.Column("capabilities",J),*provenance(),sa.CheckConstraint("status IN ('available','assigned','en_route','on_scene','unavailable')",name="ck_emergency_resource_status"))
 op.create_table("emergency_assignments",sa.Column("id",P,primary_key=True),sa.Column("incident_id",P,sa.ForeignKey("emergency_incidents.id",ondelete="CASCADE"),nullable=False),sa.Column("resource_id",P,sa.ForeignKey("emergency_resources.id",ondelete="RESTRICT"),nullable=False),sa.Column("assigned_at",sa.DateTime(timezone=True),nullable=False),sa.Column("released_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(32),nullable=False),sa.Column("notes",sa.Text),*provenance())
 op.create_table("assets",sa.Column("id",P,primary_key=True),sa.Column("catalog_id",sa.String(128),unique=True,nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("asset_type",sa.String(64),nullable=False),sa.Column("category",sa.String(64),nullable=False),sa.Column("status",sa.String(64),nullable=False),sa.Column("owner",sa.String(255)),sa.Column("description",sa.Text),sa.Column("station_id",P,sa.ForeignKey("stations.id",ondelete="SET NULL")),sa.Column("vessel_id",P,sa.ForeignKey("vessels.id",ondelete="SET NULL")),sa.Column("last_inspection",sa.DateTime(timezone=True)),sa.Column("next_inspection",sa.DateTime(timezone=True)),*provenance())
 op.create_table("vessel_positions",sa.Column("id",P,primary_key=True),sa.Column("vessel_id",P,sa.ForeignKey("vessels.id",ondelete="CASCADE"),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("position",Geometry("POINT",srid=4326),nullable=False),sa.Column("speed_kts",sa.Numeric(8,3)),sa.Column("heading_deg",sa.Numeric(6,2)),*provenance())
 for n,t,c in (("ix_emergency_events_incident_time","emergency_events",["incident_id","occurred_at"]),("ix_assignments_incident","emergency_assignments",["incident_id"]),("ix_assets_station","assets",["station_id"]),("ix_assets_vessel","assets",["vessel_id"]),("ix_vessel_positions_vessel_time","vessel_positions",["vessel_id","timestamp"])): op.create_index(n,t,c)
def downgrade():
 for t in ("vessel_positions","assets","emergency_assignments","emergency_resources","emergency_events","emergency_incidents"): op.drop_table(t)
