"""add dss report foundation

Revision ID: 32e527e342d4
Revises: eff900cd31ad
Create Date: 2026-09-26 00:38:29.716921
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '32e527e342d4'
down_revision = 'eff900cd31ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dss_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_dss_reports_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_dss_reports_catalog_id')
    )
    op.create_index('ix_dss_reports_created', 'dss_reports', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dss_reports_created', table_name='dss_reports')
    op.drop_table('dss_reports')
    # ### end Alembic commands ###
