"""add navigation risk alerts foundation

Revision ID: daae568b756a
Revises: 20260926_0005
Create Date: 2026-09-26 00:27:17.874257
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = 'daae568b756a'
down_revision = '20260926_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.String(length=128), nullable=True),
    sa.Column('trigger_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_alerts_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_alerts_catalog_id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_severity_ack', 'alerts', ['severity', 'acknowledged'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('estimated_time_hours', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fuel_liters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('iceberg_exposure', sa.String(length=64), nullable=True),
    sa.Column('sea_ice_exposure', sa.String(length=64), nullable=True),
    sa.Column('recommendation_context', sa.Text(), nullable=True),
    sa.Column('conflict_at_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_routes_status'),
    sa.CheckConstraint("objective IN ('shortest','balanced','safety')", name='ck_routes_objective'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_routes_catalog_id')
    )
    op.create_index('ix_routes_created_at', 'routes', ['created_at'], unique=False)
    op.create_index('ix_routes_geometry_gist', 'routes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('assessment_method', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('factors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_risk_status'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_route_created', 'risk_assessments', ['route_id', 'created_at'], unique=False)
    op.create_table('route_waypoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_route_waypoints_sequence')
    )
    op.create_index('ix_route_waypoints_position_gist', 'route_waypoints', ['position'], unique=False, postgresql_using='gist')
    op.create_index('ix_route_waypoints_route_sequence', 'route_waypoints', ['route_id', 'sequence_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_route_waypoints_route_sequence', table_name='route_waypoints')
    op.drop_index('ix_route_waypoints_position_gist', table_name='route_waypoints', postgresql_using='gist')
    op.drop_table('route_waypoints')
    op.drop_index('ix_risk_assessments_route_created', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_routes_geometry_gist', table_name='routes', postgresql_using='gist')
    op.drop_index('ix_routes_created_at', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_alerts_severity_ack', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
