"""add iceberg intelligence foundation

Revision ID: eff900cd31ad
Revises: daae568b756a
Create Date: 2026-09-26 00:32:48.816060
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'eff900cd31ad'
down_revision = 'daae568b756a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trajectory_model_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('interface_type', sa.String(length=128), nullable=False),
    sa.Column('input_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_model_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'model_version', name='uq_trajectory_model_version')
    )
    op.create_table('iceberg_behavior_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iceberg_id', sa.UUID(), nullable=False),
    sa.Column('profile_version', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('behavior_class', sa.String(length=64), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_behavior_status'),
    sa.ForeignKeyConstraint(['iceberg_id'], ['icebergs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iceberg_id', 'profile_version', name='uq_behavior_profile_version')
    )
    op.create_index('ix_behavior_iceberg_created', 'iceberg_behavior_profiles', ['iceberg_id', 'created_at'], unique=False)
    op.create_table('iceberg_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iceberg_a_id', sa.UUID(), nullable=False),
    sa.Column('iceberg_b_id', sa.UUID(), nullable=False),
    sa.Column('interaction_status', sa.String(length=32), nullable=False),
    sa.Column('analysis_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closest_approach_km', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('relative_velocity_kts', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('relative_heading_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('interaction_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_interaction_status_data'),
    sa.CheckConstraint("interaction_status IN ('candidate','confirmed')", name='ck_interaction_status'),
    sa.CheckConstraint('iceberg_a_id <> iceberg_b_id', name='ck_interaction_distinct_icebergs'),
    sa.ForeignKeyConstraint(['iceberg_a_id'], ['icebergs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iceberg_b_id'], ['icebergs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_a_time', 'iceberg_interactions', ['iceberg_a_id', 'analysis_at'], unique=False)
    op.create_index('ix_interactions_b_time', 'iceberg_interactions', ['iceberg_b_id', 'analysis_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interactions_b_time', table_name='iceberg_interactions')
    op.drop_index('ix_interactions_a_time', table_name='iceberg_interactions')
    op.drop_table('iceberg_interactions')
    op.drop_index('ix_behavior_iceberg_created', table_name='iceberg_behavior_profiles')
    op.drop_table('iceberg_behavior_profiles')
    op.drop_table('trajectory_model_metadata')
    # ### end Alembic commands ###
