"""add operational data foundation

Revision ID: fbb535968e86
Revises: 20260925_0003
Create Date: 2026-09-26 00:20:23.060949
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = 'fbb535968e86'
down_revision = '20260925_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocean_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('sea_surface_temperature_c', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('current_speed_ms', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('current_direction_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wave_height_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wave_period_s', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_ocean_status'),
    sa.CheckConstraint("record_type IN ('current', 'forecast')", name='ck_ocean_record_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ocean_position_gist', 'ocean_records', ['position'], unique=False, postgresql_using='gist')
    op.create_index('ix_ocean_type_time', 'ocean_records', ['record_type', 'valid_at'], unique=False)
    op.create_table('sea_ice_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_sea_ice_regions_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_sea_ice_regions_catalog_id')
    )
    op.create_index('ix_sea_ice_regions_geometry_gist', 'sea_ice_regions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('science_focus', sa.Text(), nullable=True),
    sa.Column('operational_status', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_stations_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_stations_catalog_id')
    )
    op.create_index('ix_stations_position_gist', 'stations', ['position'], unique=False, postgresql_using='gist')
    op.create_table('vessels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('call_sign', sa.String(length=64), nullable=True),
    sa.Column('polar_class', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('speed_kts', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.String(length=128), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_ahead', sa.Boolean(), nullable=False),
    sa.Column('ahead_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_vessels_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', name='uq_vessels_catalog_id')
    )
    op.create_index('ix_vessels_position_gist', 'vessels', ['position'], unique=False, postgresql_using='gist')
    op.create_table('weather_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('air_temperature_c', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wind_speed_kts', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wind_direction_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('visibility_km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wave_height_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wave_period_s', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('freezing_spray_risk', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_weather_status'),
    sa.CheckConstraint("record_type IN ('current', 'forecast')", name='ck_weather_record_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_position_gist', 'weather_records', ['position'], unique=False, postgresql_using='gist')
    op.create_index('ix_weather_type_time', 'weather_records', ['record_type', 'valid_at'], unique=False)
    op.create_table('sea_ice_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('concentration_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thickness_m', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_version', sa.String(length=128), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("data_status IN ('observed', 'forecast', 'predicted', 'simulated', 'demo', 'provisional', 'invalid')", name='ck_sea_ice_status'),
    sa.CheckConstraint("record_type IN ('current', 'forecast')", name='ck_sea_ice_record_type'),
    sa.ForeignKeyConstraint(['region_id'], ['sea_ice_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sea_ice_geometry_gist', 'sea_ice_records', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_sea_ice_type_time', 'sea_ice_records', ['record_type', 'valid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sea_ice_type_time', table_name='sea_ice_records')
    op.drop_index('ix_sea_ice_geometry_gist', table_name='sea_ice_records', postgresql_using='gist')
    op.drop_table('sea_ice_records')
    op.drop_index('ix_weather_type_time', table_name='weather_records')
    op.drop_index('ix_weather_position_gist', table_name='weather_records', postgresql_using='gist')
    op.drop_table('weather_records')
    op.drop_index('ix_vessels_position_gist', table_name='vessels', postgresql_using='gist')
    op.drop_table('vessels')
    op.drop_index('ix_stations_position_gist', table_name='stations', postgresql_using='gist')
    op.drop_table('stations')
    op.drop_index('ix_sea_ice_regions_geometry_gist', table_name='sea_ice_regions', postgresql_using='gist')
    op.drop_table('sea_ice_regions')
    op.drop_index('ix_ocean_type_time', table_name='ocean_records')
    op.drop_index('ix_ocean_position_gist', table_name='ocean_records', postgresql_using='gist')
    op.drop_table('ocean_records')
    # ### end Alembic commands ###
